tasks:
  - init: >
      poetry config virtualenvs.in-project true &&
      poetry install &&
      npm install

github:
  prebuilds:
    master: false
    pullRequests: false
    addCheck: false

vscode:
  extensions:
    - ms-python.python
