name: 🐛 Bug report
description: Report an issue with n6py
labels: [pending]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: I am doing ... What I expect is ... What actually happening is ...
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a link to a repo that can reproduce the problem you ran into. A [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) is required unless you are absolutely sure that the issue is obvious and the provided information is enough to understand the problem. If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "needs reproduction" label.
      placeholder: Reproduction URL
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: OS Platform and Distribution
      description: Please provide the Operating System and distribution verion as well as number.
      placeholder: Linux Ubuntu 21.0
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: Python version
      description: Please provide the Python version.
      placeholder: 3.9.0.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Optional if provided reproduction. Please try not to insert an image but copy paste the log text.
      render: shell
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/n6ai/n6py/blob/main/.github/CODE_OF_CONDUCT.md)
          required: true
        - label: Read the [Contributing Guidelines](https://github.com/n6ai/n6py/blob/main/.github/CONTRIBUTING.md).
          required: true
        - label: Read the [docs](https://py.n6.ai/guide).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/n6ai/n6py/issues) that reports the same bug to avoid creating a duplicate.
          required: true
        - label: Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/n6ai/n6py/discussions).
          required: true
        - label: The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
          required: true
