name: CI Release Commit

runs:
  using: composite
  steps:
    - name: Set user
      shell: bash
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Git commit
      shell: bash
      run: |
        git commit --allow-empty -m 'release: manual release'

    - name: Push to repo
      shell: bash
      run: git push origin main
